DROP TABLE IF EXISTS customers CASCADE;
DROP TABLE IF EXISTS services CASCADE;
DROP TABLE IF EXISTS orders CASCADE;

CREATE TABLE IF NOT EXISTS customers(
	id SERIAL PRIMARY KEY,
	name VARCHAR(255),
	mobile VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS services(
	id SERIAL PRIMARY KEY,
	name VARCHAR(255),
	price DOUBLE PRECISION
);

CREATE TABLE IF NOT EXISTS orders(
	id SERIAL PRIMARY KEY,
	is_completed BOOLEAN DEFAULT FALSE,
	date_at DATE DEFAULT CURRENT_TIMESTAMP,
	customer_id INT REFERENCES customers(id) ON DELETE CASCADE,
	service_id INT REFERENCES services(id) ON DELETE CASCADE
);
